-- Schema: cnpj_dados_abertos
--
-- Este script é executado pelo entrypoint oficial do PostgreSQL
-- dentro da base definida por POSTGRES_DB.

-- Segmentos do CNAE

CREATE TABLE dim_cnaes_segmento (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    secao char(1) NOT NULL,
    denominacao varchar(200) NOT NULL,
    data_inclusao date NOT NULL,

    CONSTRAINT pk_dim_cnaes_segmento
        PRIMARY KEY (id)
);

-- Cnaes

CREATE TABLE dim_cnaes (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo varchar(20) NOT NULL,
    nome varchar(200) NOT NULL,
    id_dim_cnae_segmento integer NOT NULL,
    data_inclusao date NOT NULL,

    CONSTRAINT pk_dim_cnaes
        PRIMARY KEY (id),

    CONSTRAINT fk_dim_cnaes_dim_cnaes_segmento
        FOREIGN KEY (id_dim_cnae_segmento)
        REFERENCES dim_cnaes_segmento (id)
);

-- Competências

CREATE TABLE dim_competencias (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    competencia varchar(6) NOT NULL,
    atualizado boolean NOT NULL,
    data_inclusao date NOT NULL,

    CONSTRAINT pk_dim_competencias
        PRIMARY KEY (id)
);

-- Empresas

CREATE TABLE dim_empresas (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cnpj varchar(14) NOT NULL,
    data_inclusao date NOT NULL,

    CONSTRAINT pk_dim_empresas
        PRIMARY KEY (id)
);

CREATE TABLE dim_municipios (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo varchar(20) NOT NULL,
    nome varchar(100) NOT NULL,
    uf char(2) NOT NULL,
    capital boolean NOT NULL DEFAULT false,
    data_inclusao date NOT NULL,

    CONSTRAINT pk_dim_municipios
        PRIMARY KEY (id)
);

-- Snapshot mensal das empresas

CREATE TABLE dim_empresas_mensal (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cnpj varchar(14) NOT NULL,
    razao_social varchar(200) NOT NULL,
    nome_fantasia varchar(100) NULL,
    porte smallint NOT NULL,
    situacao smallint NOT NULL,
    id_dim_empresa bigint NOT NULL,
    id_dim_cnae integer NOT NULL,
    id_dim_municipio integer NOT NULL,
    id_dim_competencia integer NOT NULL,
    simples boolean NOT NULL DEFAULT false,
    mei boolean NOT NULL DEFAULT false,
    data_inclusao date NOT NULL,

    CONSTRAINT pk_dim_empresas_mensal
        PRIMARY KEY (id),

    CONSTRAINT fk_dim_empresas_mensal_dim_empresas
        FOREIGN KEY (id_dim_empresa)
        REFERENCES dim_empresas (id),

    CONSTRAINT fk_dim_empresas_mensal_dim_cnaes
        FOREIGN KEY (id_dim_cnae)
        REFERENCES dim_cnaes (id),

    CONSTRAINT fk_dim_empresas_mensal_dim_municipios
        FOREIGN KEY (id_dim_municipio)
        REFERENCES dim_municipios (id),

    CONSTRAINT fk_dim_empresas_mensal_dim_competencias
        FOREIGN KEY (id_dim_competencia)
        REFERENCES dim_competencias (id)
);

-- Fato do snapshot mensal das empresas

CREATE TABLE fat_empresas_mensal (
    id_dim_competencia integer NOT NULL,
    id_dim_empresa bigint NOT NULL,
    nova_empresa boolean NOT NULL,
    baixada boolean NOT NULL,
    mudou_situacao boolean NOT NULL,
    entrou_simples boolean NOT NULL,
    saiu_simples boolean NOT NULL,
    data_inclusao date NOT NULL,

    CONSTRAINT pk_fat_empresas_mensal
        PRIMARY KEY (id_dim_competencia, id_dim_empresa),

    CONSTRAINT fk_fat_empresas_mensal_dim_competencias
        FOREIGN KEY (id_dim_competencia)
        REFERENCES dim_competencias (id),

    CONSTRAINT fk_fat_empresas_mensal_dim_empresas
        FOREIGN KEY (id_dim_empresa)
        REFERENCES dim_empresas (id)
);
